### **Complex Numbers and Linear Algebra Basics**
Complex numbers form the foundation of quantum mechanics because quantum states are represented as vectors with complex entries, and operations on these states are described by complex matrices. A complex number has the form `a + bi` where `i² = -1`. Extending this idea, vectors and matrices can also contain complex entries, and linear algebra provides the language to describe quantum states and their evolution. Two particularly important concepts are **eigenvalues** and **eigenvectors**, as they reveal invariant directions under linear transformations and play a fundamental role in measurement and dynamics in quantum systems.

#### **Complex Numbers in Python**

We can represent complex numbers in Python directly using the `complex` type or with NumPy arrays. We can compute their magnitude, conjugate, and phase, which are essential when describing probability amplitudes in quantum states.

In [2]:
import numpy as np
# Defining complex numbers
z1 = 3 + 4j
z2 = 1 - 2j

# Basic operations
print("z1:", z1)
print("z2:", z2)
print("Addition:", z1 + z2)
print("Multiplication:", z1 * z2)

# Magnitude and conjugate
print("Magnitude of z1:", abs(z1))
print("Conjugate of z1:", np.conjugate(z1))
print("Phase of z1 (radians):", np.angle(z1))

z1: (3+4j)
z2: (1-2j)
Addition: (4+2j)
Multiplication: (11-2j)
Magnitude of z1: 5.0
Conjugate of z1: (3-4j)
Phase of z1 (radians): 0.9272952180016122


### **Vectors and Matrices**

A vector can be thought of as a column of numbers, and in quantum computing it is used to represent states (kets). A matrix describes transformations or operators. Multiplication of matrices with vectors represents the action of an operator on a state. In NumPy, vectors and matrices are arrays, and their operations like addition, dot product, and matrix multiplication can be directly computed.


In [3]:
# Defining vectors and matrices
v = np.array([1, 2, 3])
M = np.array([[1, 2, 0],
              [0, -1, 3],
              [4, 0, 2]])

# Vector operations
print("Vector v:", v)
print("Norm of v:", np.linalg.norm(v))
print("Dot product of v with itself:", np.dot(v, v))

# Matrix operations
print("Matrix M:\n", M)
print("Matrix-Vector product:", M @ v)
print("Matrix squared:\n", M @ M)


Vector v: [1 2 3]
Norm of v: 3.7416573867739413
Dot product of v with itself: 14
Matrix M:
 [[ 1  2  0]
 [ 0 -1  3]
 [ 4  0  2]]
Matrix-Vector product: [ 5  7 10]
Matrix squared:
 [[ 1  0  6]
 [12  1  3]
 [12  8  4]]


### **Eigenvalues and Eigenvectors**

For a square matrix `A`, an eigenvector is a non-zero vector `v` such that `A v = λ v`, where `λ` is the corresponding eigenvalue. In quantum mechanics, eigenvalues often represent measurable quantities (like energy), and eigenvectors represent the states in which the system has a definite value of that quantity. Computing eigenvalues and eigenvectors reveals deep insights into the behavior of linear operators.


In [4]:
# Eigenvalue and eigenvector computation
eigvals, eigvecs = np.linalg.eig(M)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Verify one eigenpair
idx = 0
lhs = M @ eigvecs[:, idx]
rhs = eigvals[idx] * eigvecs[:, idx]
print("\nCheck for first eigenpair:")
print("M v =", lhs)
print("λ v =", rhs)

Eigenvalues: [ 3.79290291+0.j        -0.89645145+2.2353258j -0.89645145-2.2353258j]
Eigenvectors:
 [[-0.35516592+0.j         -0.31041348-0.36588084j -0.31041348+0.36588084j]
 [-0.49597197+0.j          0.70327348+0.j          0.70327348-0.j        ]
 [-0.79238183+0.j          0.02427432+0.52401512j  0.02427432-0.52401512j]]

Check for first eigenpair:
M v = [-1.34710987+0.j -1.88117353+0.j -3.00542736+0.j]
λ v = [-1.34710987+0.j -1.88117353+0.j -3.00542736+0.j]


### **Key Takeaways**

Complex numbers extend the real number system and are essential in describing amplitudes in quantum states. Vectors and matrices provide the structure for states and operators, enabling us to compute transformations and probabilities. Eigenvalues and eigenvectors are especially powerful in quantum theory, since they describe measurable quantities and invariant states. Mastering these tools is crucial before advancing to tensor products, unitary matrices, and other advanced quantum concepts.
