### **Dirac Notation and Hilbert Spaces (Bra–ket Notation, Operations, Basis States)**

Dirac notation, introduced by Paul Dirac, is the standard way to describe states and operations in quantum mechanics. A quantum state is written as a **ket** `|ψ⟩`, which corresponds to a column vector, while its dual, the **bra** `⟨ψ|`, corresponds to the conjugate transpose (row vector). Together, these notations make complex linear algebra operations compact and intuitive: inner products become `⟨ϕ|ψ⟩`, outer products become `|ψ⟩⟨ϕ|`, and operators act naturally on kets as `A|ψ⟩`.  

A *Hilbert space* is a complete vector space with an inner product, which provides the stage for quantum mechanics. Each qubit is represented in a 2-dimensional Hilbert space with basis states `|0⟩ = [1,0]ᵀ` and `|1⟩ = [0,1]ᵀ`. For multi-qubit systems, the Hilbert space grows as a tensor product of these smaller spaces, meaning that n qubits span a space of dimension 2ⁿ. This framework allows us to represent not only classical states like `|00...0⟩` but also quantum superpositions and entangled states. Dirac notation abstracts away the messy linear algebra into an elegant symbolic language.

#### **Basis States in Dirac Notation**

The standard basis for a single qubit Hilbert space consists of |0⟩ and |1⟩, which correspond to the classical bit values 0 and 1 but are represented as vectors. Any qubit state can be written as a linear combination (superposition) of these basis states, such as `|ψ⟩ = α|0⟩ + β|1⟩` with |α|² + |β|² = 1. Let’s define these states in Python.



In [2]:
import numpy as np

# Basis states
zero = np.array([[1],[0]])  # |0⟩
one = np.array([[0],[1]])   # |1⟩

print("|0⟩ =\n", zero)
print("|1⟩ =\n", one)


|0⟩ =
 [[1]
 [0]]
|1⟩ =
 [[0]
 [1]]


### **Inner and Outer Products in Dirac Notation**

In Dirac notation, the **inner product** ⟨ϕ|ψ⟩ is a complex number that measures the overlap between two states, while the **outer product** |ψ⟩⟨ϕ| is an operator that maps one state into another. This is extremely compact compared to matrix–vector multiplication in standard linear algebra. In code, the inner product corresponds to a conjugate transpose dot product, and the outer product to a matrix built from one column and one row vector.


In [3]:
# Define a superposition state |+⟩ = (|0⟩ + |1⟩)/√2
plus = (zero + one) / np.sqrt(2)

# Inner product ⟨0|+⟩
inner = zero.T.conj() @ plus
print("⟨0|+⟩ =", inner)

# Outer product |+⟩⟨0|
outer = plus @ zero.T.conj()
print("\n|+⟩⟨0| =\n", outer)


⟨0|+⟩ = [[0.70710678]]

|+⟩⟨0| =
 [[0.70710678 0.        ]
 [0.70710678 0.        ]]


### **Hilbert Spaces and Multi-Qubit Systems**

The Hilbert space for multiple qubits is formed via tensor products. For example, the two-qubit basis consists of four states: |00⟩, |01⟩, |10⟩, and |11⟩. A general two-qubit state is a linear combination of these four basis vectors. This exponential growth of Hilbert space dimension is what makes quantum computing powerful but also computationally demanding for classical simulation. In practice, we use NumPy’s `kron` function to build these spaces.


In [4]:
# Two-qubit basis states
zero_zero = np.kron(zero, zero)  # |00⟩
zero_one = np.kron(zero, one)    # |01⟩

print("|00⟩ =\n", zero_zero)
print("|01⟩ =\n", zero_one)


|00⟩ =
 [[1]
 [0]
 [0]
 [0]]
|01⟩ =
 [[0]
 [1]
 [0]
 [0]]


### **Operators in Dirac Notation**
In Dirac notation, operators are written as matrices that act on kets. For example, the Pauli-X gate flips |0⟩ to |1⟩, written as X|0⟩ = |1⟩. In Hilbert space terms, operators preserve the structure of the space while transforming states. Importantly, quantum operators are unitary, so they preserve the norm of the states.


In [6]:
# Pauli-X operator
X = np.array([[0,1],[1,0]])

# Apply X to |0⟩
result = X @ zero
print("X|0⟩ =\n", result)


X|0⟩ =
 [[0]
 [1]]


### **Key Takeaways**

- **Dirac notation** provides a compact and elegant way to express quantum states and operations.  
- **Kets |ψ⟩** represent column vectors (states), while *bras ⟨ψ|* represent row vectors (conjugate transpose).  
- **Inner products ⟨ϕ|ψ⟩** give overlaps (probability amplitudes), while *outer products |ψ⟩⟨ϕ|* form operators and projectors.  
- **Hilbert spaces** are complete vector spaces with inner products, serving as the mathematical stage for quantum mechanics.  
- **Basis states** like |0⟩ and |1⟩ span the qubit space; multi-qubit systems grow exponentially as tensor products of basis states.  
- **Operators** in Dirac notation act naturally on kets, and unitary operators preserve normalization and represent valid quantum gates.  
